# Generated by Django 3.1 on 2020-10-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0012_auto_20201005_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('billing', 'Billing'), ('shipping', 'Shipping')], max_length=120),
        ),
    ]
