# Generated by Django 3.1 on 2020-10-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0013_auto_20201009_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('shipping', 'Shipping'), ('billing', 'Billing')], max_length=120),
        ),
    ]
