# Generated by Django 3.1 on 2020-10-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0015_auto_20201015_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('shipping', 'Shipping'), ('billing', 'Billing')], max_length=120),
        ),
    ]
