# Generated by Django 3.1.2 on 2020-12-21 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productfile',
            old_name='File',
            new_name='file',
        ),
    ]
