# Generated by Django 3.1.2 on 2020-12-26 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20201222_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productfile',
            old_name='user_provided',
            new_name='user_required',
        ),
    ]
